stages:
- "Validate"
- "Build"
- "Test"

rubocop:
  image: "ruby:2.3"
  stage: "Validate"
  script:
    - gem install rubocop
    - rubocop --debug  

shellcheck:
  stage: "Validate"
  image: cardboardci/shellcheck
  script:
    - shellcheck provision/*.sh
